[package]
name = "css_parser"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
dom = { path = "../dom" }
thiserror = "1.0"
url = "2.4"
